/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new User Session.
         * @description Authenticate a User by the passed authentication credentials and create
         *     a new User Session if they are valid.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete the active User Session.
         * @description Delete the User Session being used to make the request.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new Registration.
         * @description Create a Registration for a new User. To prevent IDOR this endpoint
         *     will always return a success if the request is syntactically and
         *     semantically valid.
         */
        post: operations["createRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration/{registrationId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Registration Identifier. */
                registrationId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an existing registration.
         * @description Verify an existing Registration to create a new User.
         */
        post: operations["verifyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/degrees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a list of RIT degrees.
         * @description Get a listing of recognized RIT degree names.
         */
        get: operations["getDegrees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a listing of Users.
         * @description Get a listing of Users based off of an optional query.
         */
        get: operations["getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User Identifier. */
                userId: "me" | string;
            };
            cookie?: never;
        };
        /**
         * Get details of a User.
         * @description Get detailed information about a User.
         */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Modify details of a User.
         * @description Modify existing User details.
         */
        patch: operations["editUser"];
        trace?: never;
    };
    "/user/{userId}/profile-picture": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User Identifier. */
                userId: "me" | string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Create/Replace a User profile picture.
         * @description Create the profile picture, or update the User's profile picture.
         */
        put: operations["createUpdateUserProfilePicture"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a listing of Events.
         * @description Get a listing of Events based off of an optional query.
         */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an Event.
         * @description Create a new Event from event details.
         */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event Identifier. */
                eventId: string;
            };
            cookie?: never;
        };
        /**
         * Get an Event.
         * @description Get detailed information about an Event.
         */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        /**
         * Delete an Event.
         * @description Delete an existing Event.
         */
        delete: operations["deleteEvent"];
        options?: never;
        head?: never;
        /**
         * Modify details of an Event.
         * @description Update an Event's information.
         */
        patch: operations["updateEvent"];
        trace?: never;
    };
    "/event/{eventId}/rsvps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event Identifier. */
                eventId: string;
            };
            cookie?: never;
        };
        /**
         * Get rsvps to an Event.
         * @description Get rsvps to an existing Event.
         */
        get: operations["getEventRsvps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event/{eventId}/rsvp/me": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event Identifier. */
                eventId: string;
            };
            cookie?: never;
        };
        /**
         * Get own rsvp to an Event.
         * @description Get the current User's rsvp to an Event.
         */
        get: operations["getOwnEventRsvp"];
        /**
         * Create/Update own rsvp to an Event.
         * @description Create own rsvp to an Event if it doesn't exist, otherwise update it.
         */
        put: operations["createOrUpdateOwnEventRsvp"];
        post?: never;
        /**
         * Delete own rsvp to an Event.
         * @description Delete own rsvp to an existing Event.
         */
        delete: operations["deleteOwnEventRsvp"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Media Identifier. */
                mediaId: string;
            };
            cookie?: never;
        };
        /**
         * Get a media asset.
         * @description Get a single media asset.
         */
        get: operations["getMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A non-error response. */
        Ok: {
            /** @constant */
            ok: true;
        };
        /** @description An error response. */
        Error: {
            /** @constant */
            ok: false;
            /** @example Explanatory Error Message */
            msg?: string;
        };
        /** @description Stub User information. */
        StubUserInfo: {
            /** Format: .* */
            name: string;
        };
        /** @description Sparse User information; superset of StubUserInfo. */
        SparseUserInfo: components["schemas"]["StubUserInfo"] & {
            degrees: string[];
            /** Format: int64 */
            class: number | null;
        };
        /** @description User connection with profile picture media. */
        UserProfilePictureConnection: {
            /** Format: path */
            profilePicture: string;
        };
        /** @description Detailed User information; superset of SparseUserInfo. */
        DetailedUserInfo: components["schemas"]["SparseUserInfo"] & {
            /** Format: .* */
            aboutMe: string | null;
            /** Format: [^@].+ */
            telegramUsername: string | null;
        };
        /** @description A stub User record. */
        StubUser: {
            /** Format: uuid */
            id: string;
        } & components["schemas"]["StubUserInfo"];
        /** @description A sparse User record. */
        SparseUser: components["schemas"]["StubUser"] & components["schemas"]["SparseUserInfo"];
        /** @description A sparse User record with profile picture. */
        SparseUserWithProfilePicture: components["schemas"]["SparseUser"] & components["schemas"]["UserProfilePictureConnection"];
        /** @description A detailed User record. */
        DetailedUser: components["schemas"]["SparseUser"] & components["schemas"]["DetailedUserInfo"];
        /** @description Sparse information about a Sona. */
        SparseSona: {
            /** Format: .* */
            name?: string;
            /** Format: .* */
            species?: string | null;
        };
        /** @description A link to a social media platform. */
        SparseSocial: {
            /** Format: .+ */
            platform: string;
            /** Format: .+ */
            handle: string;
        };
        /** @description Connections with items related to a User. */
        UserConnections: {
            sonas: components["schemas"]["SparseSona"][];
            socials: components["schemas"]["SparseSocial"][];
        } & components["schemas"]["UserProfilePictureConnection"];
        /** @description -| Specialization of DetailedUserInfo where all fields are optional. */
        DetailedUserInfoPartial: components["schemas"]["DetailedUserInfo"];
        /** @description A detailed User paired with User connections. */
        DetailedUserWithConnections: components["schemas"]["DetailedUser"] & components["schemas"]["UserConnections"];
        /** @description An RSVP's connection to a User. */
        RsvpUserConnection: {
            user: components["schemas"]["StubUser"];
        };
        /**
         * @description An RSVP answer.
         * @example yes
         * @enum {string}
         */
        RsvpAnswer: "no" | "maybe" | "yes";
        /** @description Minimal RSVP information without connections. */
        SparseRsvpInfo: {
            answer: components["schemas"]["RsvpAnswer"];
        };
        /** @description An RSVP without connections. */
        SparseRsvp: {
            /** Format: uuid */
            id: string;
        } & components["schemas"]["SparseRsvpInfo"];
        /** @description A sparse RSVP - with User connection. */
        Rsvp: components["schemas"]["SparseRsvp"] & components["schemas"]["RsvpUserConnection"];
        /** @description Optional connection to Organizer/User related to an Event. */
        EventOrganizerConnection: {
            organizer: null | components["schemas"]["StubUser"];
        };
        /** @description Connection with Rsvps related to an Event. */
        EventRsvpConnections: {
            rsvps?: components["schemas"]["Rsvp"][];
        };
        /** @description Sparse Event information. */
        SparseEventInfo: {
            /** Format: .* */
            summary: string;
            location: null | "online" | string;
            /** @enum {string} */
            status: "canceled" | "tentative" | "confirmed";
            /** Format: date-time */
            dtstart?: string;
            /** Format: date-time */
            dtend?: string;
        };
        /** @description Detailed Event information; superset of SparseEventInfo. */
        DetailedEventInfo: {
            /** Format: .* */
            description: string | null;
        } & components["schemas"]["SparseEventInfo"];
        /** @description DetailedEventInfo with no required fields. */
        PartialDetailedEventInfo: components["schemas"]["DetailedEventInfo"];
        /** @description Sparse Event record. */
        SparseEventWithOrganizer: {
            /** Format: uuid */
            id: string;
        } & components["schemas"]["SparseEventInfo"] & components["schemas"]["EventOrganizerConnection"];
        /** @description Detailed Event record; superset of SparseEventWithOrganizer. */
        DetailedEvent: {
            /** Format: uuid */
            id: string;
        } & components["schemas"]["DetailedEventInfo"] & components["schemas"]["EventOrganizerConnection"] & components["schemas"]["EventRsvpConnections"];
    };
    responses: {
        /** @description Bad Request. */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized. */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Forbidden. */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description NotFound. */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict. */
        ConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unprocessable Content. */
        UnprocessableContentError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too Many Requests. */
        TooManyRequestsError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal Server Error. */
        InternalServerErrorError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description The CSRF token for requests that mutate state. */
        CsrfParameter: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User authentication credentials. */
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: ^.*$
                     * @example someguy0
                     */
                    username: string;
                    /**
                     * Format: password
                     * @example password123!
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description A Session was created. */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            400: components["responses"]["BadRequestError"];
            403: components["responses"]["ForbiddenError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header: {
                /** @description The CSRF token for requests that mutate state. */
                "X-CSRF-Token": components["parameters"]["CsrfParameter"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Session was deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    createRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User registration parameters. */
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: [a-z]+[0-9]+
                     * @example sag2234
                     */
                    ritUsername: string;
                };
            };
        };
        responses: {
            /** @description A Registration was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            400: components["responses"]["BadRequestError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    verifyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Registration Identifier. */
                registrationId: string;
            };
            cookie?: never;
        };
        /** @description Registration verification parameters. */
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: password
                     * @example 9891d1268feef7890424b173e07ad78c63f6ed5a52a5d48100f5fe093ec52040935aa445cf8f27397694a634063e5312f548b52717b9bdd6608886d6987f6374
                     */
                    code: string;
                };
            };
        };
        responses: {
            /** @description A User was created; return a Session. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            400: components["responses"]["BadRequestError"];
            404: components["responses"]["NotFoundError"];
            409: components["responses"]["ConflictError"];
            422: components["responses"]["UnprocessableContentError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    getDegrees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The collection of recognized degrees. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"] & {
                        degrees: string[];
                    };
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    getUsers: {
        parameters: {
            query?: {
                /** @description Text search query. */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The collection of Users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"] & {
                        users: components["schemas"]["SparseUserWithProfilePicture"][];
                    };
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User Identifier. */
                userId: "me" | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The User details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"] & {
                        user: components["schemas"]["DetailedUserWithConnections"];
                    };
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    editUser: {
        parameters: {
            query?: never;
            header: {
                /** @description The CSRF token for requests that mutate state. */
                "X-CSRF-Token": components["parameters"]["CsrfParameter"];
            };
            path: {
                /** @description User Identifier. */
                userId: "me" | string;
            };
            cookie?: never;
        };
        /** @description Partial update of User details. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetailedUserInfoPartial"];
            };
        };
        responses: {
            /** @description The updated User details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"] & {
                        user: components["schemas"]["DetailedUserInfo"];
                    };
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    createUpdateUserProfilePicture: {
        parameters: {
            query?: never;
            header: {
                /** @description The CSRF token for requests that mutate state. */
                "X-CSRF-Token": components["parameters"]["CsrfParameter"];
            };
            path: {
                /** @description User Identifier. */
                userId: "me" | string;
            };
            cookie?: never;
        };
        /** @description The contents of the image. */
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    media?: string;
                };
            };
        };
        responses: {
            /** @description The profile picture was updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description The profile picture was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    getEvents: {
        parameters: {
            query?: {
                /** @description Text search query. */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The collection of Events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"] & {
                        events: components["schemas"]["SparseEventWithOrganizer"][];
                    };
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header: {
                /** @description The CSRF token for requests that mutate state. */
                "X-CSRF-Token": components["parameters"]["CsrfParameter"];
            };
            path?: never;
            cookie?: never;
        };
        /** @description Full Event information. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetailedEventInfo"];
            };
        };
        responses: {
            /** @description The updated Event details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"] & {
                        /**
                         * Format: uuid
                         * @description The identifier of the created Event.
                         */
                        id: string;
                    };
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event Identifier. */
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A detailed Event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"] & {
                        event: components["schemas"]["DetailedEvent"];
                    };
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    deleteEvent: {
        parameters: {
            query?: never;
            header: {
                /** @description The CSRF token for requests that mutate state. */
                "X-CSRF-Token": components["parameters"]["CsrfParameter"];
            };
            path: {
                /** @description Event Identifier. */
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event deletion has been scheduled. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    updateEvent: {
        parameters: {
            query?: never;
            header: {
                /** @description The CSRF token for requests that mutate state. */
                "X-CSRF-Token": components["parameters"]["CsrfParameter"];
            };
            path: {
                /** @description Event Identifier. */
                eventId: string;
            };
            cookie?: never;
        };
        /** @description Partial Event information. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartialDetailedEventInfo"];
            };
        };
        responses: {
            /** @description The updated Event details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"] & {
                        event: components["schemas"]["DetailedEventInfo"];
                    };
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    getEventRsvps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event Identifier. */
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A collection of rsvps. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"] & components["schemas"]["EventRsvpConnections"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    getOwnEventRsvp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event Identifier. */
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The User's rsvp. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"] & {
                        rsvp: components["schemas"]["SparseRsvp"];
                    };
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    createOrUpdateOwnEventRsvp: {
        parameters: {
            query?: never;
            header: {
                /** @description The CSRF token for requests that mutate state. */
                "X-CSRF-Token": components["parameters"]["CsrfParameter"];
            };
            path: {
                /** @description Event Identifier. */
                eventId: string;
            };
            cookie?: never;
        };
        /** @description The rsvp answer. */
        requestBody?: {
            content: {
                "application/json": {
                    answer: components["schemas"]["RsvpAnswer"];
                };
            };
        };
        responses: {
            /** @description The rsvp was updated or did not change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description The rsvp was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    deleteOwnEventRsvp: {
        parameters: {
            query?: never;
            header: {
                /** @description The CSRF token for requests that mutate state. */
                "X-CSRF-Token": components["parameters"]["CsrfParameter"];
            };
            path: {
                /** @description Event Identifier. */
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rsvp was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
    getMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Media Identifier. */
                mediaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The media asset. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/jpeg": string;
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
            404: components["responses"]["NotFoundError"];
            429: components["responses"]["TooManyRequestsError"];
            500: components["responses"]["InternalServerErrorError"];
        };
    };
}
