title = "FurRIT"
baseURL = "https://www.furrit.us"
defaultContentLanguage = "en"

disableHugoGeneratorInject = true
disableKinds = ["rss", "sitemap", "taxonomy", "term"]

[sitemap]
disable = true

# [minify]
# minifyOutput = true

[build]
[build.buildStats]
enable = true

[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = "css"

[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
disableWatch = true
source = "hugo_stats.json"
target = "assets/notwatching/hugo_stats.json"
