title = "FurRIT"
baseURL = "https://www.furrit.us"
defaultContentLanguage = "en"

disableHugoGeneratorInject = true

disableKinds = ["rss", "sitemap", "taxonomy", "term", "section"]

[sitemap]
disable = true

# [minify]
# minifyOutput = true
