disableHugoGeneratorInject = true

[minify]
minifyOutput = true

[[cascade]]
[cascade.build]
render = "never"
list = "never"
publishResources = false

[cascade.target]
kind = "page"
path = "{**logout*}"
